### ISSUE TITLE
Table output is broken

### ISSUE THREAD

**Issue by andrey-bardashevskiy-nl** [orbinson/aem-groovy-console#41]
A simple table output script fails with an exception.

```groovy
table {
    columns('Col 1', 'Col 2')
    row('foo', 'bar')
}
```

```
20.02.2023 22:33:04.357 *ERROR* [127.0.0.1 [1676932383795] POST /bin/groovyconsole/post.json HTTP/1.1] be.orbinson.aem.groovy.console.impl.DefaultGroovyConsoleService error running script
groovy.lang.MissingPropertyException: No such property: DELEGATE_FIRST for class: be.orbinson.aem.groovy.console.extension.impl.scriptmetaclass.SlingScriptMetaClassExtensionProvider
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:161) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.extension.impl.scriptmetaclass.SlingScriptMetaClassExtensionProvider$_getScriptMetaClass_closure1$_closure4.doCall(SlingScriptMetaClassExtensionProvider.groovy:39) [aem-groovy-console-bundle:19.0.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343) [groovy:4.0.9]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88) [groovy:4.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at Script1.run(Script1.groovy:1)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.impl.DefaultGroovyConsoleService.runScript(DefaultGroovyConsoleService.groovy:75) [aem-groovy-console-bundle:19.0.1]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.servlets.ScriptPostServlet.doPost(ScriptPostServlet.groovy:63) [aem-groovy-console-bundle:19.0.1]
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:146) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.22.0]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:574) [org.apache.sling.engine:2.7.8]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45) [org.apache.sling.engine:2.7.8]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88) [org.apache.sling.engine:2.7.8]
```

**Comment by royteeuwen** [comment]
Thanks for reporting the issue! First time I see the table being used ;). Fixed in aem-groovy-console 19.0.2

**Comment by bobi** [comment]
I have developed the Intellij groovy plugin and tested the functionality :), the issue was submitted from my other account.

**Comment by royteeuwen** [comment]
@bobi super, just learned about your plugin last week because intellij suggested it, will become super handy for myself 😄! If you have any feature proposals, don't hesistate to make a ticket (or a PR 😄)

**Comment by bobi** [comment]
Seems fix didn't help, still seeing same error with 19.0.2

```
21.02.2023 19:02:06.884 *ERROR* [[0:0:0:0:0:0:0:1] [1677006126073] POST /bin/groovyconsole/post.json HTTP/1.1] be.orbinson.aem.groovy.console.impl.DefaultGroovyConsoleService error running script
groovy.lang.MissingPropertyException: No such property: DELEGATE_FIRST for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:161) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.extension.impl.scriptmetaclass.SlingScriptMetaClassExtensionProvider$_getScriptMetaClass_closure1$_closure4.doCall(SlingScriptMetaClassExtensionProvider.groovy:40) [aem-groovy-console-bundle:19.0.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343) [groovy:4.0.9]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88) [groovy:4.0.9]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328) [groovy:4.0.9]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at Script1.run(Script1.groovy:1)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.impl.DefaultGroovyConsoleService.runScript(DefaultGroovyConsoleService.groovy:75) [aem-groovy-console-bundle:19.0.2]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) [groovy:4.0.9]
	at be.orbinson.aem.groovy.console.servlets.ScriptPostServlet.doPost(ScriptPostServlet.groovy:63) [aem-groovy-console-bundle:19.0.2]
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:146) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.22.0]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:574) [org.apache.sling.engine:2.7.8]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45) [org.apache.sling.engine:2.7.8]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88) [org.apache.sling.engine:2.7.8]
```

**Comment by bobi** [comment]
You mentioned that it was fixed in 19.0.2, the first log was from 19.0.1

**Comment by royteeuwen** [comment]
> You mentioned that it was fixed in 19.0.2, the first log was from 19.0.1

Yes sorry, mislooked, it's indeed 19.0.2

**Comment by royteeuwen** [comment]
@bobi  could you please refresh the packages of the "groovy" bundle? or even more certain, restart AEM ;)? The meta classes are cached and I want to make sure that it isn't the cache that is still returning the 19.0.1 version

**Comment by royteeuwen** [comment]
@bobi  try again after 19.0.3 is released (might still need that restart)

**Comment by bobi** [comment]
@royteeuwen thank you, 19.0.3 works like a charm
